[project]
name = "leetcode"
version = "0.1.0"
description = "LeetCode solutions in Python"
authors = [
    { name = "Alexandre Cirilo", email = "38657258+alxdrcirilo@users.noreply.github.com" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
